## 1.5.3　NumPyの算術計算

In [1]:
import numpy as np
x = np.array( [1.0, 2.0, 3.0] )
y = np.array( [2.0, 4.0, 6.0] )
x+y

array([3., 6., 9.])

In [2]:
x-y

array([-1., -2., -3.])

In [3]:
x/y

array([0.5, 0.5, 0.5])

In [4]:
x*y

array([ 2.,  8., 18.])

In [7]:
x /2.0

array([0.5, 1. , 1.5])

In [9]:
me={'height':180}
me['height']

180

In [11]:
me['weight']=70
print(me)

{'height': 180, 'weight': 70}


In [12]:
a=1
if a>0 :
	print(1)   
else:
	print(2)

1


In [14]:
for i in [1,2,3]:
		print('why')

why
why
why


In [33]:
def hello():
		print("Hello World!")

m=hello()

Hello World!


In [39]:
A = np.array( [[1, 2], [2, 3]] )
print(A)

[[1 2]
 [2 3]]


In [40]:
A.shape

(2, 2)

In [41]:
A.dtype

dtype('int32')

In [42]:
B = np.array( [[3, 0], [0, 6]] )
A+B

array([[4, 2],
       [2, 9]])

In [44]:
A*10

array([[10, 20],
       [20, 30]])

In [43]:
A*B

array([[ 3,  0],
       [ 0, 18]])